import:
	io.lumine.mythic.bukkit.BukkitAPIHelper
	
	org.bukkit.inventory.ItemStack
	org.bukkit.Material
	
	de.tr7zw.changeme.nbtapi.NBTItem

function castSkill(e: entity, s: string):
	new BukkitAPIHelper().castSkill({_e}, {_s})

function getItem(p: player i: item) :: item:
	return {_p}.getInventory().getItemInMainHand()

function getNbt(t: item, d: string) :: string:
	set {_nbt} to new NbtItem({_i})
	if {_nbt}.hasKey({_d}) == true:
		return {_nbt}.getString({_d})
	else:
		return null